import { mkdirSync, writeFileSync } from 'node:fs';
import { charmTokens, charmDefinition, generateCss } from '@charm-ux/theming';

const outDir = 'dist/themes/charm';

mkdirSync(outDir, { recursive: true });

// Main theme CSS (uses light-dark() function)
writeFileSync(`${outDir}/theme.css`, charmTokens.css || '');
writeFileSync(`${outDir}/reset.css`, charmTokens.cssReset || '');
writeFileSync(`${outDir}/utility-classes.css`, charmTokens.cssUtilities || '');
writeFileSync(`${outDir}/TOKENS.md`, charmTokens.tokensMarkdown || '');

// Dark theme CSS (forces dark mode via color-scheme)
const darkThemeCss = `/* Generated by @charm-ux/theming - DO NOT EDIT */
:root {
  color-scheme: dark;
}
`;
writeFileSync(`${outDir}/dark-theme.css`, darkThemeCss);

// Selector-based theme CSS (uses data attributes instead of prefers-color-scheme)
const selectorThemeCss = generateCss(charmDefinition, {
  prefix: 'charm',
  useLightDarkFunction: false,
  useDataAttributes: true,
});
writeFileSync(`${outDir}/selector-theme.css`, selectorThemeCss);

// Write tokens JSON - separate light/dark only if there are light/dark variations
if (charmTokens.hasLightDarkTokens) {
  const tokensDir = `${outDir}/tokens`;
  mkdirSync(tokensDir, { recursive: true });
  writeFileSync(`${tokensDir}/light.json`, charmTokens.tokensLightJson || '');
  writeFileSync(`${tokensDir}/dark.json`, charmTokens.tokensDarkJson || '');
  console.log(
    `Theme generated: ${outDir}/theme.css, reset.css, utility-classes.css, dark-theme.css, selector-theme.css, tokens/light.json, tokens/dark.json, TOKENS.md`
  );
} else {
  writeFileSync(`${outDir}/tokens.json`, charmTokens.tokensJson || '');
  console.log(
    `Theme generated: ${outDir}/theme.css, reset.css, utility-classes.css, dark-theme.css, selector-theme.css, tokens.json, TOKENS.md`
  );
}
