import { ThemeConfiguration } from './types.js';

export const defaultConfig: ThemeConfiguration = {
  tokenPrefix: '',
  outDir: './theme',
  resetFileName: 'reset.css',
  themeFileName: 'theme.css',
  darkThemeFileName: 'dark-theme.css',
  selectorThemeFileName: 'selector-theme.css',
  cssUtilityClassesFileName: 'utility-classes.css',
  helpersFileName: 'token-helpers.js',
  helpersOutDir: '',
  extendedResetStyles: '',
  extendedTokens: '',
  extendedDarkTokens: '',
  extendedSemanticTokens: '',
  lightThemeSelector: '',
  darkThemeSelector: '',
  skipHelpers: false,
  skipReset: false,
  skipNonSelectorThemes: false,
  tokens: {
    semantics: {
      body: {
        bgColor: 'inherit',
        fgColor: 'inherit',
        fontFamily: 'inherit',
        fontSize: 'inherit',
        fontWeight: 'inherit',
        lineHeight: 'inherit',
      },
      defaultBorder: {
        size: 'inherit',
        color: 'inherit',
        style: 'inherit',
      },
      button: {
        bgColor: 'inherit',
        borderColor: 'inherit',
        borderSize: 'inherit',
        borderStyle: 'inherit',
        borderRadius: 'inherit',
        fgColor: 'inherit',
        fontWeight: 'inherit',
        paddingX: 'inherit',
        paddingY: 'inherit',
        shadow: 'inherit',
        activeFgColor: 'inherit',
        activeBorderColor: 'inherit',
        activeBgColor: 'inherit',
        activeShadow: 'inherit',
        disabledBgColor: 'inherit',
        disabledBorderColor: 'inherit',
        disabledFgColor: 'inherit',
        disabledShadow: 'inherit',
        focusBgColor: 'inherit',
        focusBorderColor: 'inherit',
        focusFgColor: 'inherit',
        focusShadow: 'inherit',
        hoverBgColor: 'inherit',
        hoverBorderColor: 'inherit',
        hoverFgColor: 'inherit',
        hoverShadow: 'inherit',
      },
      form: {
        borderColor: 'inherit',
        borderSize: 'inherit',
        borderStyle: 'inherit',
        borderRadius: 'inherit',
        bgColor: 'inherit',
        contentGap: 'inherit',
        paddingX: 'inherit',
        paddingY: 'inherit',
      },
      formControl: {
        bgColor: 'inherit',
        borderColor: 'inherit',
        borderRadius: 'inherit',
        borderSize: 'inherit',
        borderStyle: 'inherit',
        fgColor: 'inherit',
        fontSize: 'inherit',
        iconGap: 'inherit',
        inputHeight: 'inherit',
        placeholderColor: 'inherit',
        paddingX: 'inherit',
        paddingY: 'inherit',
        disabledBgColor: 'inherit',
        disabledBorderColor: 'inherit',
        disabledFgColor: 'inherit',
        disabledOpacity: 'inherit',
        disabledPlaceholderColor: 'inherit',
        invalidBgColor: 'inherit',
        invalidBorderColor: 'inherit',
        invalidFgColor: 'inherit',
        invalidPlaceholderColor: 'inherit',
        invalidMessageFgColor: 'inherit',
        focusBgColor: 'inherit',
        focusBorderColor: 'inherit',
        focusFgColor: 'inherit',
        helpText: {
          fgColor: 'inherit',
          fontSize: 'inherit',
          fontWeight: 'inherit',
          gap: 'inherit',
        },
        label: {
          fgColor: 'inherit',
          fontSize: 'inherit',
          fontWeight: 'inherit',
          gap: 'inherit',
          requiredIndicatorGap: 'inherit',
        },
      },
      heading: {
        fgColor: 'inherit',
        fontFamily: 'inherit',
        fontWeight: 'inherit',
        lineHeight: 'inherit',
      },
      link: {
        fgColor: 'inherit',
        decoration: 'inherit',
        activeFgColor: 'inherit',
        activeDecoration: 'inherit',
        hoverFgColor: 'inherit',
        hoverDecoration: 'inherit',
        focusFgColor: 'inherit',
        focusDecoration: 'inherit',
        visitedFgColor: 'inherit',
        visitedDecoration: 'inherit',
      },
      focusOutline: {
        color: 'inherit',
        offset: 'inherit',
        size: 'inherit',
        style: 'inherit',
      },
    },
  },
};
